[tool.poetry]
name = "langflow-discord"
version = "0.0.1"
description = "A langflow extension to provide discord integration"
authors = ["Langflow <contact@langflow.org>"]
maintainers = [
    "Carlos Coelho <carlos@langflow.org>",
    "Cristhian Zanforlin <cristhian.lousa@gmail.com>",
    "Gabriel Almeida <gabriel@langflow.org>",
    "Igor Carvalho <igorr.ackerman@gmail.com>",
    "Lucas Eduoli <lucaseduoli@gmail.com>",
    "Otávio Anovazzi <otavio2204@gmail.com>",
    "Rodrigo Nader <rodrigo@langflow.org>",
]
repository = "https://github.com/langflow-ai/langflow"
license = "MIT"
readme = "README.md"
keywords = ["nlp", "langchain", "openai", "gpt", "discord"]
packages = [{ include = "src" }]
include = ["pyproject.toml", "README.md", "langflow/**/*"]
documentation = "https://docs.langflow.org"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastapi = "^0.110.1"
httpx = "*"
uvicorn = "^0.29.0"
gunicorn = "^22.0.0"
pydantic = "^2.5.0"
pydantic-settings = "^2.1.0"
websockets = "*"
typer = "^0.12.0"
cachetools = "^5.3.1"
platformdirs = "^4.2.0"
python-multipart = "^0.0.7"
orjson = "3.10.0"
passlib = "^1.7.4"
discord-py = "^2.3.2"
soundfile = "^0.12.1"
ffmpeg = "^1.4"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["tests", "integration"]
console_output_style = "progress"
filterwarnings = ["ignore::DeprecationWarning"]
log_cli = true
markers = ["async_test"]

[tool.mypy]
namespace_packages = true
mypy_path = "langflow"
ignore_missing_imports = true

[tool.ruff]
exclude = ["src/discord/src/alembic/*"]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
